name: Cypress Tests
on: [push]
jobs: 
   cypress-run: 
       runs-on: ubuntu-latest
       steps:
          - name: Cypress.io
            uses: cypress-io/github-action@v4.1.1
            with: 
                install: npm install
                start: npm start
               
